#server:
#  port: 9091

spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      name: userservices
      logging:
        level:
          org.springframework.cloud.config: DEBUG