spring:
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      name: userspreferences
      logging:
        level:
          org.springframework.cloud.config: DEBUG