server:
  port: 9092
spring:
  application:
    name: userspreferences
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

#spring:
#  profiles:
#    active: default
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: userspreferences
#      logging:
#        level:
#          org.springframework.cloud.config: DEBUG